{
  "resourceType" : "ValueSet",
  "id" : "2.16.840.1.113883.3.3616.200.110.102.6080",
  "meta" : {
    "versionId" : "9",
    "lastUpdated" : "2023-12-21T17:43:03.000-05:00",
    "profile" : [
      "http://hl7.org/fhir/StructureDefinition/shareablevalueset",
      "http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/computable-valueset-cqfm",
      "http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/publishable-valueset-cqfm"
    ]
  },
  "extension" : [
    {
      "url" : "http://hl7.org/fhir/StructureDefinition/valueset-author",
      "valueString" : "Clinical Architecture"
    },
    {
      "url" : "http://hl7.org/fhir/StructureDefinition/resource-lastReviewDate",
      "valueDate" : "2023-06-21"
    },
    {
      "url" : "http://hl7.org/fhir/StructureDefinition/valueset-effectiveDate",
      "valueDate" : "2022-07-27"
    }
  ],
  "url" : "http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.3616.200.110.102.6080",
  "identifier" : [
    {
      "system" : "urn:ietf:rfc:3986",
      "value" : "urn:oid:2.16.840.1.113883.3.3616.200.110.102.6080"
    }
  ],
  "version" : "20220727",
  "name" : "COVID19SNOMEDValueSetForCoronavirusInfectionsExcludingSARSCoV2",
  "title" : "COVID19 SNOMED Value Set for Coronavirus Infections, Excluding SARS CoV 2",
  "status" : "retired",
  "experimental" : false,
  "date" : "2023-06-21T18:16:37-04:00",
  "publisher" : "Clinical Architecture",
  "jurisdiction" : [
    {
      "coding" : [
        {
          "system" : "urn:iso:std:iso:3166",
          "code" : "US"
        }
      ]
    }
  ],
  "purpose" : "(Clinical Focus: This set of values contains terms related to non SARS-CoV-2 human coronavirus infections.),(Data Element Scope: ),(Inclusion Criteria: Includes coronavirus infections, disease due to coronavirus, and coronavirus suspected as cause of infection.),(Exclusion Criteria: Excludes SARS-CoV-2 infection.)",
  "compose" : {
    "include" : [
      {
        "system" : "http://snomed.info/sct",
        "concept" : [
          {
            "code" : "186758000",
            "display" : "Coronavirus as the cause of diseases classified to other chapters (disorder)"
          },
          {
            "code" : "187467005",
            "display" : "[X]Coronavirus infection, unspecified (disorder)"
          },
          {
            "code" : "441590008",
            "display" : "Pneumonia caused by Severe acute respiratory syndrome coronavirus (disorder)"
          },
          {
            "code" : "651000146102",
            "display" : "Middle East respiratory syndrome (disorder)"
          },
          {
            "code" : "700217006",
            "display" : "Suspected coronavirus infection (situation)"
          },
          {
            "code" : "713084008",
            "display" : "Pneumonia caused by Human coronavirus (disorder)"
          },
          {
            "code" : "84101006",
            "display" : "Human coronavirus (organism)"
          }
        ]
      }
    ]
  },
  "expansion" : {
    "identifier" : "urn:uuid:fe3f0d58-c4f5-49f2-af3c-5db991bf6bf1",
    "timestamp" : "2024-06-14T16:21:34-04:00",
    "total" : 5,
    "contains" : [
      {
        "system" : "http://snomed.info/sct",
        "version" : "http://snomed.info/sct/731000124108/version/20240301",
        "code" : "441590008",
        "display" : "Pneumonia caused by Severe acute respiratory syndrome coronavirus (disorder)"
      },
      {
        "system" : "http://snomed.info/sct",
        "version" : "http://snomed.info/sct/731000124108/version/20240301",
        "code" : "651000146102",
        "display" : "Middle East respiratory syndrome (disorder)"
      },
      {
        "system" : "http://snomed.info/sct",
        "version" : "http://snomed.info/sct/731000124108/version/20240301",
        "code" : "700217006",
        "display" : "Suspected coronavirus infection (situation)"
      },
      {
        "system" : "http://snomed.info/sct",
        "version" : "http://snomed.info/sct/731000124108/version/20240301",
        "code" : "713084008",
        "display" : "Pneumonia caused by Human coronavirus (disorder)"
      },
      {
        "system" : "http://snomed.info/sct",
        "version" : "http://snomed.info/sct/731000124108/version/20240301",
        "code" : "84101006",
        "display" : "Human coronavirus (organism)"
      }
    ]
  }
}
